package com.gehj.okhttp_netframe.download.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadEntityDaoConfig;

    private final DownLoadEntityDao downLoadEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadEntityDaoConfig = daoConfigMap.get(DownLoadEntityDao.class).clone();
        downLoadEntityDaoConfig.initIdentityScope(type);

        downLoadEntityDao = new DownLoadEntityDao(downLoadEntityDaoConfig, this);

        registerDao(DownLoadEntity.class, downLoadEntityDao);
    }
    
    public void clear() {
        downLoadEntityDaoConfig.clearIdentityScope();
    }

    public DownLoadEntityDao getDownLoadEntityDao() {
        return downLoadEntityDao;
    }

}
